# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 486501e2749873eb725a8a9e44a694011573982458a0f161265e7cf4fe00cc19e7f25a56341498d40a499142b321f3a8c1fe7d6fc01bca035cc72a09fd443330

test:
  secret_key_base: 64f6af9a66a8e968e1af875f0d702499ef4f3fc01df66ce39c9f77b91ceb47cde63635c88eb1fb7b3ca4ca1a925fb90ffeb47213387401cb13c5b7031f7774e4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
